version: "2.1"
services:
  admin:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: admin
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  admin-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: admin-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  appconfigs:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: appconfigs
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  appconfigs-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: appconfigs-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis
  articles:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: articles
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  articles-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: articles-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  assets:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: assets
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  bookmarks:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: bookmarks
    links:
      - linkerd
    depends_on:
      - es
      - redis

  bookmarks-writer:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: bookmarks-writer
    links:
      - linkerd
    depends_on:
      - nsolid-console
      - es
      - redis

  categories:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: categories
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  categories-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: categories-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  dai:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: dai
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  deploy:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: deploy
    links:
      - linkerd
    depends_on:
      - es
      - redis

  deploy-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: deploy-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - redis

  dpp-proxy:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: dpp-proxy
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  dpp-proxy-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: dpp-proxy-draft
    links:
      - linkerd
    depends_on:
      - nsolid-console
      - redis

  favorites:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: favorites
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  feeds:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: feeds
    environment:
      CACHEMANAGER_DEFAULT_EXPIRATION_TTL: 608400000
      CACHEMANAGER_DEFAULT_FAIL_TTL: 120000
      CACHEMANAGER_DELAY_AFTER_MAX_FAILS: 1800000
      CACHEMANAGER_FAIL_RETRIES: 2
      CONCURRENCY: 10
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  foryou:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: foryou
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  geo:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: geo
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  geo-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: geo-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  legacy:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: legacy
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  liveplayer:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: liveplayer
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  mvpds:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: mvpds
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  mvpds-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: mvpds-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  notifications:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: notifications
    links:
    - linkerd
    depends_on:
    - nsolid-console
    - redis
    - dynamo

  persons:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: persons
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  persons-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: persons-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  photos:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: photos
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  photos-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: photos-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  vodplayer:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: vodplayer
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  promos:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: promos
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  promos-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: promos-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  screens:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: screens
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  screens-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: screens-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  search:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: search
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  seasons:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: seasons
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  seasons-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: seasons-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  seo:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: seo
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  seo-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: seo-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  series:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: series
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  series-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: series-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  snapshots:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: snapshots
    links:
      - linkerd
    depends_on:
      - elasticmq
      - dynamo

  text:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: text
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  text-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: text-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  upnext:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: upnext
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  video:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: video
    links:
      - linkerd
    depends_on:
      - es
      - nsolid-console
      - redis

  video-draft:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: video-draft
    links:
      - linkerd
    depends_on:
      - elasticmq
      - es
      - indexer
      - mongo
      - nsolid-console
      - redis

  viewer:
    extends:
      file: ${COMPOSE_FOLDER}/services.yml
      service: viewer
    links:
      - linkerd
    depends_on:
      - es
      - dynamo
      - nsolid-console
      - redis

  # INDEXERS
  indexer:
    extends:
      file: ${COMPOSE_FOLDER}/indexers.yml
      service: indexer
    depends_on:
      - es
      - elasticmq
      - redis
      - dynamo

  # SHARED
  mongo:
    extends:
      file: ${COMPOSE_FOLDER}/shared.yml
      service: mongo

  es:
    extends:
      file: ${COMPOSE_FOLDER}/shared.yml
      service: es

  # BASE SERVICES
  elasticmq:
    image: fingershock/elasticmq:0.9.3
    mem_limit: 512m
    ports:
      - "9324:9324"

  fakes3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569
    volumes:
      - ./docker/s3:/fakes3_root

  nsolid-console:
    image: nodesource/nsolid-console:carbon-alpine-3.1.1
    ports:
      - 9001:9001
      - 9002:9002
      - 9003:9003
      - 6753:6753
    volumes:
      - ./docker/nsolid/console:/var/lib/nsolid/console

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  dynamo:
    image: fndcg/dynamodb
    build:
      context: ./docker/dynamodb
      dockerfile: Dockerfile
    ports:
      - "10199:10199"

  proxy:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: fndcg/dcgproxy:local
    mem_limit: 512m
    environment:
       - "CONSUL_KV_PREFIX=nginx"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/www:/www

  linkerd:
    image: buoyantio/linkerd:1.1.3
    command: ['/config.yaml']
    links:
      - consul
      - proxy
    volumes:
      - ./docker/linkerd/config.yml:/config.yaml
      - ./docker/linkerd/config:/io.buoyant/linkerd/1.1.3/config
    ports:
      - "9990:9990"
      - "4140:4140"
    depends_on:
      - registrator

  consul:
    image: consul:latest
    command: agent -server -ui -bind=0.0.0.0 -client=0.0.0.0 -bootstrap-expect=1 -node=conul_server
    volumes:
      - ./docker/consul/data:/consul/data
      - ./docker/consul/consulKVTemplate.json:/consul/consulKVTemplate.json
    mem_limit: 512m
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  registrator:
    command: -ip=0.0.0.0 -internal -cleanup -deregister=always -retry-attempts=-1 consul://consul:8500
    hostname: registrator_local
    image: gliderlabs/registrator:latest
    mem_limit: 512m
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  statsd:
    image: samuelebistoletti/docker-statsd-influxdb-grafana:latest
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
      - "22022:22"
      - "8125:8125/udp"

  tests-controller:
    image: fndcg/e2econtroller:local
    build:
      context: ./packages/dcgapi-tests-controller
      dockerfile: Dockerfile
    environment:
      AWS_S3_ENDPOINT: test-results.s3.amazonaws.com:4569
      AWS_SQS_ENDPOINT: http://elasticmq:9324/
      BOOKMARKS_AND_FAVORITES_ENDPOINT: "http://foxprofile-staging.us-east-1.elasticbeanstalk.com"
      E2E_DCG_VERSION: "_v1"
      ES_HOST: ""
      LINKERD_HOST: "linkerd"
      NODE_ENV: local
      PORT: 8080
      PROFILE_ENDPOINT: "https://dev.api2.fox.com/v2.0"
      TEST_RESULTS_BUCKET: test-results
      USE_LOCAL: ""
    ports:
      - "8080:8080"
    links:
      - fakes3:test-results.s3.amazonaws.com
    depends_on:
      - elasticmq
      - fakes3
    volumes:
      - ./node_modules:/opt/app/node_modules
      - ./packages:/opt/app/packages
      - ./package.json:/opt/app/package.json
